OUTPUT_DIR: "./exp_cuhk"
INPUT:
  DATASET: "CUHK-SYSU"
  DATA_ROOT: "../../../datasets/ps/ssm"
  BATCH_SIZE_TRAIN: 2
  NUM_WORKERS_TRAIN: 2
SOLVER:
  MAX_EPOCHS: 20
MODEL:
  LOSS:
    LUT_SIZE: 5532
    CQ_SIZE: 5000