OUTPUT_DIR: "./exp_mvn"
INPUT:
  DATASET: "MovieNet"
  DATA_ROOT: "../../../datasets/ps/mvn"
  BATCH_SIZE_TRAIN: 5
  NUM_WORKERS_TRAIN: 5
SOLVER:
  MAX_EPOCHS: 5
MODEL:
  LOSS:
    LUT_SIZE: 2088
    CQ_SIZE: 2000