OUTPUT_DIR: "./exp_mvn"
INPUT:
  DATASET: "MVN"
  DATA_ROOT: "../../../datasets/ps/mvn"
  BATCH_SIZE_TRAIN: 15
  NUM_WORKERS_TRAIN: 15
  MIN_SIZE: 240
  MAX_SIZE: 720
SOLVER:
  MAX_EPOCHS: 16
  BASE_LR: 0.009
MODEL:
  LOSS:
    LUT_SIZE: 2088
    CQ_SIZE: 2000
