OUTPUT_DIR: "./exp_mvn"
INPUT:
  DATASET: "MVN"
  DATA_ROOT: "../../../datasets/ps/mvn"
  BATCH_SIZE_TRAIN: 5
  NUM_WORKERS_TRAIN: 5
  MIN_SIZE: 240
  MAX_SIZE: 720
SOLVER:
  MAX_EPOCHS: 10
  BASE_LR: 0.003
MODEL:
  LOSS:
    LUT_SIZE: 3087
    CQ_SIZE: 3000
